name: SonarCloud analysis

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug file structure
        run: ls -R

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Mcflurrins_adpro_eshop
            -Dsonar.organization=mcflurrins
            -Dsonar.sources=src/main/java # Change this to your actual source folder
            -Dsonar.tests=src/test/java   # Change this if your tests are elsewhere
            -Dsonar.verbose=true
